# Generated by Django 3.2.18 on 2023-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
    ]
