# Generated by Django 3.2.18 on 2023-04-01 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название товара')),
                ('price', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(999999)], verbose_name='Цена товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение товара')),
                ('availability', models.BooleanField(default=False)),
                ('categories', models.CharField(choices=[('Искусство', 'Искусство'), ('Цифровые товары', 'Цифровые товары'), ('Одежда', 'Одежда')], default='Цифровые товары', max_length=255)),
            ],
        ),
    ]
