# Generated by Django 3.2.18 on 2023-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0002_alter_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_item_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='ordersstatus',
            name='order_status_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID статуса заказа'),
        ),
        migrations.AlterField(
            model_name='productsdescription',
            name='product_desc_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='productstypes',
            name='product_type',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Тип товара'),
        ),
    ]
