# Generated by Django 3.2.18 on 2023-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0002_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Магазины')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес магазина')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='Контакты')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение магазина')),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='availability',
            field=models.BooleanField(default=False, verbose_name='Доступно на складе'),
        ),
    ]
