# Generated by Django 3.2.18 on 2023-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0003_auto_20230401_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Магазин'),
        ),
    ]
