# Generated by Django 3.2.18 on 2023-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_auto_20230415_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdescription',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название товара'),
        ),
    ]
