# Generated by Django 3.2.18 on 2023-04-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_auto_20230401_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
