# Generated by Django 4.2 on 2023-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_auto_20230401_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='shop',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
