# Generated by Django 3.2.18 on 2023-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
