# Generated by Django 3.2.18 on 2023-04-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0006_products_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
