# Generated by Django 3.2.18 on 2023-04-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_shop_slug_shop_time_added'),
        ('shopper', '0006_shop_time_added'),
    ]

    operations = [
    ]
