# Generated by Django 4.2 on 2023-04-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_shop_slug_shop_time_added'),
        ('shopper', '0006_shop_time_added'),
    ]

    operations = [
    ]
