# Generated by Django 3.2.18 on 2023-04-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_merge_20230406_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopper.shop'),
        ),
    ]
