# Generated by Django 3.2.18 on 2023-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_rename_product_slug_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdescription',
            name='product_size',
            field=models.CharField(blank=True, choices=[('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47')], max_length=100, null=True, verbose_name='Размер обуви'),
        ),
    ]
