# Generated by Django 3.2.18 on 2023-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0008_alter_productsdescription_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdescription',
            name='main_material',
            field=models.CharField(blank=True, choices=[('текстиль', 'текстиль'), ('хлопок', 'хлопок'), ('резина', 'резина'), ('кожа', 'кожа'), ('кожзам', 'кожзам'), ('замша', 'замша')], max_length=100, null=True, verbose_name='Основной материал'),
        ),
    ]
