# Generated by Django 3.2.18 on 2023-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0009_productsdescription_main_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdescription',
            name='sole_thickness',
            field=models.IntegerField(blank=True, choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5)], default=1, null=True, verbose_name='Толщина подошвы'),
        ),
    ]
