# Generated by Django 3.2.18 on 2023-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0009_alter_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
