# Generated by Django 3.2.18 on 2023-04-09 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0011_auto_20230409_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('o_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО клиента')),
                ('o_mail', models.CharField(blank=True, max_length=100, verbose_name='Электронная почта клиента')),
                ('o_phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон клиента')),
                ('delivery_type', models.CharField(blank=True, max_length=100, verbose_name='Тип доставки')),
                ('o_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-o_create_date'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('p_code', models.IntegerField(blank=True, default=0, verbose_name='Код товара')),
                ('p_add_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления товара')),
                ('p_price', models.IntegerField(blank=True, default=0, verbose_name='Цена товара')),
                ('p_quantity', models.IntegerField(blank=True, default=0, verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-p_add_date', 'p_quantity', 'p_price'],
            },
        ),
        migrations.CreateModel(
            name='ProductsTypes',
            fields=[
                ('p_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='Тип товара')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование типа товара')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Тип товаров',
                'ordering': ['p_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='shopperuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='shopperuser',
            name='create_date',
        ),
        migrations.AddField(
            model_name='shopperuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopperuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+999999999' (до 15 символом).", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='shopperuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='shopperuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='shopperuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='ProductsDescription',
            fields=[
                ('p_desc_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('p_name', models.CharField(blank=True, max_length=100, verbose_name='Название товара')),
                ('p_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка товара')),
                ('p_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер обуви')),
                ('p_other_attrs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительные аттрибуты')),
                ('p_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shopper.products')),
                ('p_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopper.productstypes')),
            ],
            options={
                'verbose_name': 'Описание товара',
                'verbose_name_plural': 'Описание товаров',
                'ordering': ['p_desc_id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersStatus',
            fields=[
                ('os_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID статуса заказа')),
                ('o_status', models.CharField(choices=[('Заказ создан', 'Заказ создан'), ('Заказ оплачен', 'Заказ оплачен'), ('Заказ доставлен', 'Заказ доставлен')], default='Заказ создан', max_length=100, verbose_name='Статус заказа')),
                ('os_last_update', models.DateTimeField(auto_now=True, verbose_name='Отслеживание изменения статуса заказа')),
                ('o_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopper.orders')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статус заказов',
                'ordering': ['os_last_update'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('oi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shopper.orders')),
                ('p_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shopper.products')),
            ],
        ),
    ]
