# Generated by Django 3.2.18 on 2023-04-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0011_auto_20230417_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории')),
                ('category_name', models.CharField(blank=True, choices=[('женская обувь', 'женская обувь'), ('мужская обувь', 'мужская обувь'), ('детская обувь', 'детская обувь')], max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='shopper.Category'),
        ),
    ]
