# Generated by Django 3.2.18 on 2023-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0012_auto_20230409_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdescription',
            name='p_images',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение товара'),
        ),
    ]
