# Generated by Django 3.2.18 on 2023-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0012_auto_20230417_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='productsdescription',
            name='seasons',
            field=models.CharField(blank=True, choices=[('лето-весна', 'лето-весна'), ('зима-осень', 'зима-осень')], max_length=100, null=True, verbose_name='Сезонность'),
        ),
    ]
