# Generated by Django 3.2.18 on 2023-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0013_auto_20230417_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdescription',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('Китай', 'Китай'), ('Тайвань', 'Тайвань'), ('Индия', 'Индия'), ('Пакистан', 'Пакистан')], max_length=100, null=True, verbose_name='Страна производитель'),
        ),
    ]
