# Generated by Django 3.2.18 on 2023-04-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0013_productsdescription_p_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Связь заказ - товар', 'verbose_name_plural': 'Связь заказы - товары'},
        ),
        migrations.AlterField(
            model_name='ordersstatus',
            name='o_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopper.orders', unique=True),
        ),
        migrations.AlterField(
            model_name='productsdescription',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopper.products', unique=True),
        ),
        migrations.AlterField(
            model_name='productsdescription',
            name='p_images',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение товара'),
        ),
    ]
