# Generated by Django 3.2.18 on 2023-04-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0015_products_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID комментария')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголокок комментария')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст комментария')),
                ('date_created', models.DateTimeField(auto_now=True, null=True, verbose_name='Время создания комментария')),
                ('date_edited', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время изменения комментария')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopper.products')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date_edited', '-date_created'],
            },
        ),
    ]
