# Generated by Django 4.2 on 2023-04-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_merge_20230405_2028'),
        ('shopper', '0016_auto_20230409_1828'),
    ]

    operations = [
    ]
