# Generated by Django 3.2.18 on 2023-04-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0017_imageproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображение товаров'},
        ),
        migrations.RemoveField(
            model_name='productsdescription',
            name='product_images',
        ),
    ]
