# Generated by Django 3.2.18 on 2023-04-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0018_auto_20230418_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Отображается на главной'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopper.products'),
        ),
    ]
